// <auto-generated />
using System;
using Eng_Backend.DAL.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eng_Backend.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217143017_AddProblemAndQuizEntities")]
    partial class AddProblemAndQuizEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eng_Backend.DAL.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConcurrencyStamp = "efa73bb2-f247-40f9-a6d1-5a5f1d627076",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5770),
                            Description = "System Administrator with full access",
                            IsSystemRole = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5770)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ConcurrencyStamp = "9ee2c501-0013-46db-a0c4-7884e16ee92f",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5810),
                            Description = "Default user role with basic permissions",
                            IsSystemRole = true,
                            Name = "User",
                            NormalizedName = "USER",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5810)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ConcurrencyStamp = "40c0cd63-ac7f-406d-9647-ae2e244347d6",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5820),
                            Description = "Generic role to assign dynamic permissions",
                            IsSystemRole = false,
                            Name = "GenericRole",
                            NormalizedName = "GENERICROLE",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5820)
                        });
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.DocumentRole", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocumentId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("DocumentRoles");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Category = "Users",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5920),
                            Description = "Yeni kullanıcı oluşturabilir",
                            DisplayName = "Kullanıcı Oluşturma",
                            Name = "Users.Create",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5920)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Category = "Users",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5930),
                            Description = "Kullanıcıları görüntüleyebilir",
                            DisplayName = "Kullanıcı Görüntüleme",
                            Name = "Users.Read",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5930)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Category = "Users",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5930),
                            Description = "Kullanıcı bilgilerini güncelleyebilir",
                            DisplayName = "Kullanıcı Güncelleme",
                            Name = "Users.Update",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5930)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Category = "Users",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5930),
                            Description = "Kullanıcıları silebilir",
                            DisplayName = "Kullanıcı Silme",
                            Name = "Users.Delete",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5930)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Category = "Roles",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5930),
                            Description = "Yeni rol oluşturabilir",
                            DisplayName = "Rol Oluşturma",
                            Name = "Roles.Create",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5930)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Category = "Roles",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5930),
                            Description = "Rolleri görüntüleyebilir",
                            DisplayName = "Rol Görüntüleme",
                            Name = "Roles.Read",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5930)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Category = "Roles",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5940),
                            Description = "Rol bilgilerini güncelleyebilir",
                            DisplayName = "Rol Güncelleme",
                            Name = "Roles.Update",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5940)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Category = "Roles",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5940),
                            Description = "Rolleri silebilir",
                            DisplayName = "Rol Silme",
                            Name = "Roles.Delete",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5940)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Category = "Permissions",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5940),
                            Description = "Yeni yetki tanımlayabilir",
                            DisplayName = "Yetki Oluşturma",
                            Name = "Permissions.Create",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5940)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Category = "Permissions",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5940),
                            Description = "Yetkileri görüntüleyebilir",
                            DisplayName = "Yetki Görüntüleme",
                            Name = "Permissions.Read",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5940)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Category = "Permissions",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5940),
                            Description = "Yetki bilgilerini güncelleyebilir",
                            DisplayName = "Yetki Güncelleme",
                            Name = "Permissions.Update",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5940)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Category = "Permissions",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5940),
                            Description = "Yetkileri silebilir",
                            DisplayName = "Yetki Silme",
                            Name = "Permissions.Delete",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5940)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Category = "Posts",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5950),
                            Description = "Yeni içerik oluşturabilir",
                            DisplayName = "İçerik Oluşturma",
                            Name = "Posts.Create",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5950)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Category = "Posts",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5950),
                            Description = "İçerik güncelleyebilir",
                            DisplayName = "İçerik Güncelleme",
                            Name = "Posts.Update",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5950)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Category = "Posts",
                            CreatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5950),
                            Description = "İçerik silebilir",
                            DisplayName = "İçerik Silme",
                            Name = "Posts.Delete",
                            UpdatedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(5950)
                        });
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.ProblemAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ProblemId");

                    b.ToTable("ProblemAssignments");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectAnswerIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6010)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6020)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6020)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6020)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6020)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000006"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6020)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000007"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6020)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000008"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6020)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000009"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6020)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000010"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6030)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000011"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6030)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000012"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6030)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000013"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6030)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000014"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6030)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000015"),
                            GrantedAt = new DateTime(2025, 12, 17, 14, 30, 17, 658, DateTimeKind.Utc).AddTicks(6030)
                        });
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Solution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.SolutionFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId");

                    b.ToTable("SolutionFiles");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SelectedAnswerIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId", "QuestionId")
                        .IsUnique();

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.UserScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("QuizPoints")
                        .HasColumnType("integer");

                    b.Property<int>("QuizzesCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("TaskPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TasksCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserScores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Document", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.DocumentRole", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.Document", "Document")
                        .WithMany("DocumentRoles")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Problem", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.ProblemAssignment", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eng_Backend.DAL.Entities.Problem", "Problem")
                        .WithMany("Assignments")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Question", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.RolePermission", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Solution", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ProblemAssignment", "Assignment")
                        .WithMany("Solutions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assignment");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.SolutionFile", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.Solution", "Solution")
                        .WithMany("Files")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.UserAnswer", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.UserScore", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.ApplicationRole", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Document", b =>
                {
                    b.Navigation("DocumentRoles");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Problem", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.ProblemAssignment", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Question", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Solution", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
