// <auto-generated />
using System;
using Eng_Backend.DAL.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eng_Backend.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eng_Backend.DAL.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConcurrencyStamp = "4498b82e-e974-4717-a5f0-2d3858da5122",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8360),
                            Description = "System Administrator with full access",
                            IsSystemRole = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8360)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ConcurrencyStamp = "a4bd60ad-c3bc-4ddc-a317-8b15bf89eb44",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8380),
                            Description = "Default user role with basic permissions",
                            IsSystemRole = true,
                            Name = "User",
                            NormalizedName = "USER",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8380)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ConcurrencyStamp = "5f162fd6-9663-47b8-b0e1-5a33e8cf8276",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8380),
                            Description = "Generic role to assign dynamic permissions",
                            IsSystemRole = false,
                            Name = "GenericRole",
                            NormalizedName = "GENERICROLE",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8380)
                        });
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Category = "Users",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8440),
                            Description = "Yeni kullanıcı oluşturabilir",
                            DisplayName = "Kullanıcı Oluşturma",
                            Name = "Users.Create",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8440)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Category = "Users",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8440),
                            Description = "Kullanıcıları görüntüleyebilir",
                            DisplayName = "Kullanıcı Görüntüleme",
                            Name = "Users.Read",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8440)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Category = "Users",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8440),
                            Description = "Kullanıcı bilgilerini güncelleyebilir",
                            DisplayName = "Kullanıcı Güncelleme",
                            Name = "Users.Update",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8450)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Category = "Users",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8450),
                            Description = "Kullanıcıları silebilir",
                            DisplayName = "Kullanıcı Silme",
                            Name = "Users.Delete",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8450)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Category = "Roles",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8450),
                            Description = "Yeni rol oluşturabilir",
                            DisplayName = "Rol Oluşturma",
                            Name = "Roles.Create",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8450)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Category = "Roles",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8450),
                            Description = "Rolleri görüntüleyebilir",
                            DisplayName = "Rol Görüntüleme",
                            Name = "Roles.Read",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8450)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Category = "Roles",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8450),
                            Description = "Rol bilgilerini güncelleyebilir",
                            DisplayName = "Rol Güncelleme",
                            Name = "Roles.Update",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8450)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Category = "Roles",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8460),
                            Description = "Rolleri silebilir",
                            DisplayName = "Rol Silme",
                            Name = "Roles.Delete",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8460)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Category = "Permissions",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8460),
                            Description = "Yeni yetki tanımlayabilir",
                            DisplayName = "Yetki Oluşturma",
                            Name = "Permissions.Create",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8460)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Category = "Permissions",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8460),
                            Description = "Yetkileri görüntüleyebilir",
                            DisplayName = "Yetki Görüntüleme",
                            Name = "Permissions.Read",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8460)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Category = "Permissions",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8470),
                            Description = "Yetki bilgilerini güncelleyebilir",
                            DisplayName = "Yetki Güncelleme",
                            Name = "Permissions.Update",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8470)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Category = "Permissions",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8470),
                            Description = "Yetkileri silebilir",
                            DisplayName = "Yetki Silme",
                            Name = "Permissions.Delete",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8470)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Category = "Posts",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8480),
                            Description = "Yeni içerik oluşturabilir",
                            DisplayName = "İçerik Oluşturma",
                            Name = "Posts.Create",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8480)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Category = "Posts",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8480),
                            Description = "İçerik güncelleyebilir",
                            DisplayName = "İçerik Güncelleme",
                            Name = "Posts.Update",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8480)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Category = "Posts",
                            CreatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8480),
                            Description = "İçerik silebilir",
                            DisplayName = "İçerik Silme",
                            Name = "Posts.Delete",
                            UpdatedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8480)
                        });
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8530)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8530)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8530)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8530)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8530)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000006"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8540)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000007"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8540)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000008"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8540)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000009"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8540)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000010"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8540)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000011"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8540)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000012"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8540)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000013"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8550)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000014"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8550)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000015"),
                            GrantedAt = new DateTime(2025, 11, 20, 19, 36, 18, 588, DateTimeKind.Utc).AddTicks(8550)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.RolePermission", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Eng_Backend.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.ApplicationRole", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Eng_Backend.DAL.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
